[package]
name = "sddc-extio"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.29"

[dependencies]
anyhow.workspace = true
num-complex.workspace = true
rustfft.workspace = true
realfft.workspace = true
wide.workspace = true
log.workspace = true
sddc.workspace = true
chrono = { workspace = true, optional = true }

