[workspace]
members = [
    "src/sddc"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["SDDC Lab"]
license = "LGPL-2.1-or-later"

[workspace.dependencies]
nusb = { version = "0.2.1"}
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }

# Logging
log = "0.4"
env_logger = "0.11"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Utilities
parking_lot = "0.12"

[profile.release]
lto=true
opt-level = 3
strip = true
debug = true
panic = "abort"
codegen-units = 1