[package]
name = "sddc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage="http://www.rx-888.com"
description="A native Rust driver for the rx-888 family of software-defined radios (SDR)."

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[build-dependencies]
cbindgen = "0.29"

[dependencies]
anyhow.workspace = true
nusb.workspace = true
log.workspace = true
chrono = { workspace = true, optional = true }
clap.workspace = true
cbindgen = "0.29"

[dev-dependencies]
serial_test = "3"
parameterized = "2"
env_logger = "0.11"

[[bin]]
name = "capture_raw_data"
required-features = []

[[bin]]
name = "usb_throughput_test"
required-features = []

[features]
default=[]
cbinding=[]
