[package]
name = "sddc"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[build-dependencies]
cbindgen = "0.29"

[dependencies]
anyhow.workspace = true
nusb.workspace = true
num-complex.workspace = true
rustfft.workspace = true
realfft.workspace = true
wide.workspace = true
log.workspace = true
chrono = { workspace = true, optional = true }
clap.workspace = true

[dev-dependencies]
serial_test = "3"
parameterized = "2"
env_logger = "0.11"

[[bin]]
name = "capture_raw_data"
required-features = []

[[bin]]
name = "usb_throughput_test"
required-features = []

[features]
test-utils = []

